In [1]:
import pandas as pd

C:\Users\shupe\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\shupe\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.4' currently installed).
  from pandas.core import (

In [4]:
GFR_DF=pd.read_csv("CCF_QHS_Datasets/GFR.csv")

In [27]:
GFR_DF

,Age,Height,Weight,Female,Diabetes,African American,Systolic,Diastolic,Stroke,Cardiac,...,Epired,HCT Intraop,Duration,EBL,RBC,Crystalloid,Colloid,TVol,sCR Post,eCcr Post
0,81.6,70.9,99.8,0,0,0.0,136.0,64.0,0,0,...,NaN,34.0,260,200,0,2900,1000,169.34,1.9,42.60
1,78.7,66.0,86.0,1,0,0.0,159.0,69.0,0,0,...,0.0,40.0,355,400,0,4600,0,316.47,1.1,56.55
2,80.2,74.8,69.9,0,0,0.0,137.0,65.0,0,1,...,0.0,29.0,283,600,350,7100,1000,570.18,1.4,41.48
3,89.4,68.0,90.0,0,1,0.0,144.0,68.0,0,0,...,0.0,32.0,269,450,0,8400,1000,468.26,1.2,52.70
4,76.0,70.9,75.0,0,0,0.0,141.0,68.0,0,1,...,0.0,51.0,156,150,0,4900,0,169.87,1.0,66.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,58.0,NaN,82.3,1,0,1.0,118.0,62.0,1,0,...,0.0,32.0,248,250,0,2800,1000,190.92,0.6,132.69
484,62.8,74.8,113.9,0,0,1.0,168.0,100.0,0,1,...,0.0,38.0,420,400,0,2900,0,178.23,9.6,12.72
485,62.4,65.0,102.0,1,0,NaN,119.0,NaN,0,1,...,0.0,35.0,199,350,0,5400,1000,208.10,0.6,155.84
486,62.1,70.9,82.1,0,0,0.0,NaN,NaN,0,0,...,0.0,25.0,274,1200,345,6600,1000,441.92,0.6,148.12
487,66.6,70.9,117.0,0,0,NaN,198.0,88.0,0,0,...,0.0,38.0,355,700,0,3500,0,176.99,1.0,119.32

In [11]:
GFR_DF.columns

Index(['Age', 'Height', 'Weight', 'Female', 'Diabetes', 'African American',
       'Systolic', 'Diastolic', 'Stroke', 'Cardiac', 'Heart Repair', 'Afib',
       'HTN', 'CHF', 'Pulm', 'Renal Insuff', 'Statins', 'sCR Pre', 'eCcr Pre',
       'Dye', 'Dye Volume', 'Warm', 'Acetylcystine', 'Emergency', 'Epired',
       'HCT Intraop', 'Duration', 'EBL', 'RBC', 'Crystalloid', 'Colloid',
       'TVol', 'sCR Post', 'eCcr Post'],
      dtype='object')

In [15]:
GFR_DF["Epired"].value_counts()

Epired
0.0    439
1.0     48
Name: count, dtype: int64

In [18]:
GFR_DF["Emergency"].value_counts()

Emergency
0    467
1     21
Name: count, dtype: int64

#### More patients died than patients who actually had emergency surgery; maybe more patients needed to be elevated to emergency status

In [29]:
#Duration is in minutes
GFR_DF["Duration"].describe()

count    488.000000
mean     300.297131
std      105.471367
min       77.000000
25%      226.750000
50%      281.000000
75%      361.000000
max      738.000000
Name: Duration, dtype: float64

In [28]:
GFR_DF["Duration"].median()

281.0